name: Release Data

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  update-data:
    name: Release Data
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build TZResScraper
        run: dotnet build -c Release -nologo

      - name: Install Languages
        shell: pwsh
        run: scripts\Install-Languages.ps1

      - name: Collect Display Names
        run: dotnet run --project TZResScraper/TZResScraper.csproj -c Release --no-build

      - name: Release Data
        uses: softprops/action-gh-release@v2
        with:
          files: tzinfo.json
      